import { NextRequest, NextResponse } from 'next/server';
import { ingestSession } from '@/lib/services/session-ingester';
import { analyzeSession, findCriticalPath } from '@/lib/services/debug-analyzer';
import { computeExecutionFacts } from '@/lib/services/execution-facts';
import { estimateAgentCost, formatTokens, formatDuration, formatCost } from '@/lib/utils';
import type { Session, Agent } from '@/types/session';
import type { DebugAlert } from '@/types/analytics';

function agentDisplayName(agent: Agent): string {
  if (agent.description) return agent.description.slice(0, 60);
  return agent.subagentType || agent.type;
}

function generateMarkdown(session: Session, alerts: DebugAlert[], criticalPath: Agent[]): string {
  const lines: string[] = [];

  lines.push(`# Session Report: ${session.project}`);
  lines.push(`**Session ID:** ${session.id}`);
  lines.push(`**Created:** ${new Date(session.created).toLocaleString()}`);
  lines.push(`**Status:** ${session.status}`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Agents | ${session.totalAgents} |`);
  lines.push(`| Total Tokens | ${formatTokens(session.totalTokens)} |`);
  lines.push(`| Total Tool Calls | ${session.totalToolCalls} |`);
  lines.push(`| Wall Clock | ${formatDuration(session.duration.wallClock)} |`);
  lines.push(`| Agent Time | ${formatDuration(session.duration.agentTime)} |`);
  lines.push(`| Parallelism | ${session.duration.parallelismFactor.toFixed(1)}× |`);
  lines.push(`| Estimated Cost | ${formatCost(session.estimatedCost.total)} |`);
  lines.push(`| Primary Model | ${session.primaryModel} |`);
  lines.push('');

  lines.push('## Cost by Model');
  lines.push('');
  lines.push('| Model | Cost |');
  lines.push('|-------|------|');
  for (const [model, cost] of Object.entries(session.estimatedCost.byModel).sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${model} | ${formatCost(cost)} |`);
  }
  lines.push('');

  lines.push('## Agents');
  lines.push('');
  lines.push('| # | Agent | Model | Tokens | Duration | Cost |');
  lines.push('|---|-------|-------|--------|----------|------|');
  const sorted = [...session.agents].sort((a, b) => {
    const ca = estimateAgentCost(a.tokenUsage, a.model);
    const cb = estimateAgentCost(b.tokenUsage, b.model);
    return cb - ca;
  });
  sorted.forEach((a, i) => {
    const cost = estimateAgentCost(a.tokenUsage, a.model);
    lines.push(`| ${i + 1} | ${agentDisplayName(a)} | ${a.model.replace('claude-', '')} | ${formatTokens(a.tokenUsage.total)} | ${formatDuration(a.durationMs)} | ${formatCost(cost)} |`);
  });
  lines.push('');

  if (criticalPath.length > 1) {
    lines.push('## Critical Path');
    lines.push('');
    lines.push(criticalPath.map(a => `${agentDisplayName(a)} (${formatDuration(a.durationMs)})`).join(' → '));
    lines.push('');
    lines.push(`**Total:** ${formatDuration(criticalPath.reduce((s, a) => s + a.durationMs, 0))}`);
    lines.push('');
  }

  if (alerts.length > 0) {
    lines.push('## Debug Alerts');
    lines.push('');
    for (const alert of alerts) {
      const icon = alert.severity === 'critical' ? '🔴' : alert.severity === 'warning' ? '🟡' : '🔵';
      lines.push(`- ${icon} **${alert.title}** — ${alert.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by AgentWatch on ${new Date().toLocaleString()}*`);

  return lines.join('\n');
}

function generateHtml(session: Session, alerts: DebugAlert[], criticalPath: Agent[]): string {
  const md = generateMarkdown(session, alerts, criticalPath);
  const escaped = md
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Session Report — ${session.project}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; max-width: 900px; margin: 0 auto; padding: 40px 20px; line-height: 1.6; }
    h1 { color: #e6edf3; border-bottom: 1px solid #21262d; padding-bottom: 8px; }
    h2 { color: #e6edf3; margin-top: 32px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { text-align: left; padding: 6px 12px; border: 1px solid #21262d; font-size: 13px; }
    th { background: #161b22; color: #8b949e; font-weight: 600; }
    td { background: #0d1117; }
    strong { color: #e6edf3; }
    code { background: #161b22; padding: 2px 6px; border-radius: 3px; font-size: 12px; }
    hr { border: none; border-top: 1px solid #21262d; margin: 32px 0; }
    li { margin: 4px 0; }
    a { color: #58a6ff; }
  </style>
</head>
<body>
  <p>${escaped}</p>
</body>
</html>`;
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const format = req.nextUrl.searchParams.get('format') || 'json';
    const session = ingestSession(id);

    if (!session) {
      return NextResponse.json({ error: 'Session not found' }, { status: 404 });
    }

    const alerts = analyzeSession(session);
    const criticalPath = findCriticalPath(session);
    const facts = computeExecutionFacts(session);

    if (format === 'markdown') {
      const md = generateMarkdown(session, alerts, criticalPath);
      return new NextResponse(md, {
        headers: {
          'Content-Type': 'text/markdown; charset=utf-8',
          'Content-Disposition': `attachment; filename="session-${id.slice(0, 8)}.md"`,
        },
      });
    }

    if (format === 'html') {
      const html = generateHtml(session, alerts, criticalPath);
      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Content-Disposition': `attachment; filename="session-${id.slice(0, 8)}.html"`,
        },
      });
    }

    // JSON — include execution facts
    return new NextResponse(JSON.stringify({ session, alerts, criticalPath: criticalPath.map(a => a.id), facts }, null, 2), {
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'Content-Disposition': `attachment; filename="session-${id.slice(0, 8)}.json"`,
      },
    });
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
